# Generated by Django 2.0.3 on 2018-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('assigned', models.CharField(default='Cap redactor assignat', max_length=140)),
                ('priority', models.CharField(max_length=140)),
            ],
        ),
    ]
