# Generated by Django 2.0.3 on 2018-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Graphic_reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=140)),
                ('file', models.FileField(upload_to='articles')),
                ('images', models.ManyToManyField(to='Graphic_reporter.Image')),
            ],
        ),
    ]
