# Generated by Django 2.0.3 on 2018-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_comentat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=140)),
                ('file', models.FileField(upload_to='commented_articles')),
            ],
        ),
    ]
