# Generated by Django 2.0.3 on 2018-05-04 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copywriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Head_copywriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Layout_designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Subscriber', 'Subscriber'), ('Copywriter', 'Copywriter'), ('Head_copywriter', 'Head_copywriter'), ('Graphic_reporter', 'Graphic_reporter'), ('Layout_designer', 'Layout_designer')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AddField(
            model_name='layout_designer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AddField(
            model_name='head_copywriter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AddField(
            model_name='graphic_reporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AddField(
            model_name='copywriter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
    ]
