# Generated by Django 2.0.3 on 2018-03-18 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptor',
            new_name='Copywriter',
        ),
        migrations.RenameModel(
            old_name='Reporter_grafic',
            new_name='Graphic_reporter',
        ),
        migrations.RenameModel(
            old_name='Redactor',
            new_name='Head_copywriter',
        ),
        migrations.RenameModel(
            old_name='Redactor_cap',
            new_name='Machine_designer',
        ),
        migrations.RenameModel(
            old_name='Maquetador',
            new_name='Subscriber',
        ),
    ]
