# Generated by Django 2.0.3 on 2018-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20180318_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copywriter',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='graphic_reporter',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='head_copywriter',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='machine_designer',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='rol',
        ),
    ]
