# Generated by Django 2.0.3 on 2018-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20180318_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='copywriter',
            name='speciality',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
