# Generated by Django 2.0.3 on 2018-03-23 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0004_copywriter_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Subscriber', 'Subscriber'), ('Copywriter', 'Copywriter'),
                                                   ('Head_copywriter', 'Head_copywriter'),
                                                   ('Graphic_reporter', 'Graphic_reporter'),
                                                   ('Machine_designer', 'Machine_designer')], max_length=30)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='copywriter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AlterField(
            model_name='graphic_reporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AlterField(
            model_name='head_copywriter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AlterField(
            model_name='machine_designer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.User_profile'),
        ),
    ]
