# Generated by Django 2.0.3 on 2018-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts', '0006_auto_20180323_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('Subscriber', 'Subscriber'), ('Copywriter', 'Copywriter'),
                                            ('Head_copywriter', 'Head_copywriter'),
                                            ('Graphic_reporter', 'Graphic_reporter'),
                                            ('Layout_designer', 'Layout_designer')], max_length=30),
        ),
    ]
