# Generated by Django 2.0.3 on 2018-05-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=140)),
                ('bio', models.CharField(max_length=140)),
                ('image', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('type', models.CharField(max_length=140)),
                ('assigned', models.CharField(default='Cap redactor assignat', max_length=140)),
                ('priority', models.CharField(default='', max_length=140)),
                ('state', models.CharField(choices=[('Nova notícia', 'Nova notícia'), ('Assignada', 'Assignada'), ('Per validar', 'Per validar'), ('Acceptat', 'Acceptat'), ('Rebutjada', 'Rebutjada'), ('Comentat', 'Comentat')], default='Nova notícia', max_length=140)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AfeNews.Author')),
            ],
        ),
    ]
