# Generated by Django 2.0.3 on 2018-03-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfeNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(),
        ),
    ]
