# Generated by Django 2.0.3 on 2018-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfeNews', '0002_auto_20180318_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='assigned',
            field=models.CharField(default='Cap redactor assignat', max_length=140),
        ),
        migrations.AddField(
            model_name='new',
            name='priority',
            field=models.CharField(default='', max_length=140),
        ),
    ]
