# Generated by Django 2.0.3 on 2018-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AfeNews', '0003_auto_20180420_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='tovalidate',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
