# Generated by Django 2.0.3 on 2018-04-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AfeNews', '0004_new_tovalidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tovalidate',
            field=models.BooleanField(default=False),
        ),
    ]
