# Generated by Django 2.0.3 on 2018-05-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AfeNews', '0003_auto_20180427_0746'),
        ('AfeNews', '0005_auto_20180425_1608'),
    ]

    operations = [
    ]
