# Generated by Django 2.0.3 on 2018-04-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AfeNews', '0005_auto_20180425_1608'),
        ('AfeNews', '0003_auto_20180427_0746'),
    ]

    operations = [
    ]
