# Generated by Django 2.0.3 on 2018-05-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AfeNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to='images')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Política', 'Política'), ('Esports', 'Esports'), ('Natura', 'Natura'), ('Musica', 'Musica'), ('Art', 'Art'), ('Vehicle', 'Vehicle'), ('Videojocs', 'Videojocs'), ('Altres', 'Altres')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('To do', 'To do'), ('Send', 'Send'), ('Validated', 'Validated'), ('To change', 'To change')], max_length=30)),
                ('comment', models.CharField(blank=True, default='Cap comentari', max_length=280)),
                ('images', models.ManyToManyField(to='Graphic_reporter.Image')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AfeNews.New')),
            ],
        ),
    ]
