# Generated by Django 2.0.3 on 2018-05-01 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Graphic_reporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('Política', 'Política'), ('Esports', 'Esports'), ('Natura', 'Natura'), ('Musica', 'Musica'), ('Art', 'Art'), ('Vehicle', 'Vehicle'), ('Videojocs', 'Videojocs'), ('Altres', 'Altres')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
